#syria
df_syrianconflict <- read.csv(file = "syria_google_trend.csv")
df_syrianconflict <- df_syrianconflict %>% 
  mutate(date = ym(date),
         syria_trend_google = as.numeric(ifelse(syria_trend_google == "<1", 0, syria_trend_google)),
         syria_trend_google_lag_01 = Lag(syria_trend_google, 1),
         syria_trend_google_lag_02 = Lag(syria_trend_google, 2),
         syria_trend_google_lag_03 = Lag(syria_trend_google, 3),
         syria_trend_google_lag_04 = Lag(syria_trend_google, 4),
         syria_trend_google_lag_05 = Lag(syria_trend_google, 5),
         syria_trend_google_lag_06 = Lag(syria_trend_google, 6),
         syria_trend_google_lag_07 = Lag(syria_trend_google, 7),
         syria_trend_google_lag_08 = Lag(syria_trend_google, 8),
         syria_trend_google_lag_09 = Lag(syria_trend_google, 9),
         syria_trend_google_lag_10 = Lag(syria_trend_google, 10),
         syria_trend_google_lag_11 = Lag(syria_trend_google, 11),
         syria_trend_google_lag_12 = Lag(syria_trend_google, 12),
         syria_trend_google_lag_13 = Lag(syria_trend_google, 13),
         syria_trend_google_lag_14 = Lag(syria_trend_google, 14),
         syria_trend_google_lag_15 = Lag(syria_trend_google, 15),
         syria_trend_google_lag_16 = Lag(syria_trend_google, 16),
         syria_trend_google_lag_17 = Lag(syria_trend_google, 17),
         syria_trend_google_lag_18 = Lag(syria_trend_google, 18),
         syria_trend_google_lag_19 = Lag(syria_trend_google, 19),
         syria_trend_google_lag_20 = Lag(syria_trend_google, 20),
         syria_trend_google_lag_21 = Lag(syria_trend_google, 21),
         syria_trend_google_lag_22 = Lag(syria_trend_google, 22),
         syria_trend_google_lag_23 = Lag(syria_trend_google, 23),
         syria_trend_google_lag_24 = Lag(syria_trend_google, 24))
